[package]
name    = "parry2d"
version = "0.8.0"
authors = [ "Sébastien Crozet <developer@crozet.re>" ]

description = "2 dimensional collision detection library in Rust."
documentation = "http://parry.rs/docs"
homepage = "http://parry.rs"
repository = "https://github.com/dimforge/parry"
readme = "README.md"
keywords = [ "collision", "geometry", "distance", "ray", "convex" ]
categories = [ "science", "game-development", "mathematics", "wasm"]
license = "Apache-2.0"
edition = "2021"

[badges]
maintenance = { status = "actively-developed" }

[features]
default = [ "required-features", "std" ]
required-features = [ "dim2", "f32" ]
std     = [ "nalgebra/std", "slab", "rustc-hash", "simba/std", "arrayvec/std" ]
dim2    = [ ]
f32     = [ ]
serde-serialize = [ "serde", "nalgebra/serde-serialize", "arrayvec/serde" ]
simd-stable = [ "simba/wide", "simd-is-enabled" ]
simd-nightly = [ "simba/packed_simd", "simd-is-enabled" ]
enhanced-determinism = [ "simba/libm_force", "indexmap" ]
cuda   = [ "cust_core", "cust", "nalgebra/cuda" ]

# Do not enable this feature directly. It is automatically
# enabled with the "simd-stable" or "simd-nightly" feature.
simd-is-enabled = [ ]

[lib]
name = "parry2d"
path = "../../src/lib.rs"
required-features = [ "required-features" ]

[dependencies]
either          = { version = "1", default-features = false }
bitflags        = "1"
downcast-rs     = { version = "1", default-features = false }
num-traits      = { version = "0.2", default-features = false }
smallvec        = "1"
slab            = { version = "0.4", optional = true }
arrayvec        = { version = "0.7", default-features = false }
simba           = { version = "0.7", default-features = false }
nalgebra        = { version = "0.30", default-features = false, features = [ "libm" ] }
approx          = { version = "0.5", default-features = false }
serde           = { version = "1.0", optional = true, features = ["derive"]}
num-derive      = "0.3"
indexmap        = { version = "1", features = [ "serde-1" ], optional = true }
rustc-hash      = { version = "1", optional = true }
cust_core       = { version = "0.1", optional = true }
spade           = { version = "2" } # Make this optional?

[target.'cfg(not(target_os = "cuda"))'.dependencies]
cust = { version = "0.3", optional = true }

[dev-dependencies]
simba = { version = "0.7", default-features = false, features = [ "partial_fixed_point_support" ] }
oorandom = "11"
